// blood-donation-system-vue/src/views/identity/Login.vue
<template>
    <div class="row">
        <div class="col-sm-1 col-md-3"></div>
        <div class="col-sm-10 col-md-6">
            <h4>Use a local account to log in.</h4>
            <hr />
            <div class="form-group">
                <label for="Input_Email">Email</label>
                <input
                    class="form-control"
                    type="email"
                    id="Input_Email"
                    v-model="email"
                />
            </div>
            <div class="form-group">
                <label for="Input_Password">Password</label>
                <input
                    class="form-control"
                    type="password"
                    id="Input_Password"
                    v-model="password"
                />
            </div>
            <div class="form-group">
                <button
                    @click="loginClicked()"
                    type="submit"
                    class="btn btn-primary"
                >
                    Log in
                </button>
            </div>
        </div>
        <div class="col-sm-1 col-md-3"></div>
    </div>
</template>
<script lang="ts">
import { Options, Vue } from "vue-class-component";
import store from "@/store/index";

@Options({
    components: {},
    props: {},
})
export default class Login extends Vue {
    email: string = "admin@bloody.ee";
    password: string = "Foo.bar1";

    async loginClicked(): Promise<void> {
        // console.log(this.email, this.password, event);

        await store.dispatch("logIn", {
            email: this.email,
            password: this.password,
        });

        if (store.state.token != null) {
            this.$router.push("/");
        }
        /*
        var result = await this.axios.get("https://localhost:5001/api/v1/ContactTypes");
        console.log(result);
        */
    }
}
</script>

// blood-donation-system-react/src/containers/identity/Login.tsx
import { useContext, useState } from "react";
import { Redirect } from "react-router";
import { Link } from "react-router-dom";
import Alert, { EAlertClass } from "../../components/Alert";
import { AppContext } from "../../context/AppContext";
import { IdentityService } from "../../services/identity-service";

const Login = () => {
    const appState = useContext(AppContext);

    const [loginData, setLoginData] = useState({ email: '', password: '' });
    const [alertMessage, setAlertMessage] = useState('');

    const logInClicked = async (e: Event) => {
        e.preventDefault();
        if (loginData.email === '' || loginData.password === '') {
            setAlertMessage('Empty email or pawwsord!');
        };

        let response = await IdentityService.Login('/Account/Login', loginData);
        if (!response.ok) {
            setAlertMessage(response.messages!);
        } else {
            setAlertMessage('');
            appState.setAuthInfo(response.data!.token, response.data!.firstname, response.data!.lastname);
        }
    }

    return (
        <>
            { appState.token !== null ? <Redirect to="/" /> : null}
            <h1>Log in</h1>
            <form>
                <div className="row">
                    <div className="col-md-6">
                        <section>
                            <hr />
                            <Alert show={alertMessage !== ''} message={alertMessage} alertClass={EAlertClass.Danger} />
                            <div className="form-group">
                                <label htmlFor="Input_Email">Email</label>
                                <input value={loginData.email} onChange={e => setLoginData({ ...loginData, email: e.target.value })} className="form-control" type="email" id="Input_Email" name="Input.Email" placeholder="user@example.com"  autoComplete="username" />
                            </div>
                            <div className="form-group">
                                <label htmlFor="Input_Password">Password</label>
                                <input value={loginData.password} onChange={e => setLoginData({ ...loginData, password: e.target.value })} className="form-control" type="password" id="Input_Password" name="Input.Password" placeholder="Input your current password..." autoComplete="current-password" />
                            </div>
                            <div className="form-group">
                                <button onClick={(e) => logInClicked(e.nativeEvent)} type="submit" className="btn btn-primary">Log in</button>
                                <Link className="ml-2" id="register" to="/Identity/Register">Register new user</Link> 
                            </div>
                        </section>
                    </div>
                </div>
            </form>
            
        </>
    );
}

export default Login;
