// blood-donation-system-react/src/containers/identity/Register.tsx
import { useContext, useState } from "react";
import { Redirect } from "react-router";
import { Link } from "react-router-dom";
import Alert, { EAlertClass } from "../../components/Alert";
import { AppContext } from "../../context/AppContext";
import { IdentityService } from "../../services/identity-service";

const Register = () => {
    const validationTemplate = {
        error: "",
        email: "",
        password: "",
        confirmPassword: "",
        firstname: "",
        lastname: ""
    }

    const appState = useContext(AppContext);

    const [registerData, setFormValues] = useState({
         email: '',
         password: '',
         confirmPassword: '',
         firstname: '',
         lastname: ''});

    const [alertMessage, setAlertMessage] = useState(validationTemplate);

    const handleValidation = () => {
        let formIsValid = true;

        setAlertMessage(validationTemplate);

        const emailRe = /^(([^<>()[\].,;:\s@"]+(\.[^<>()[\],;:\s@"]+)*)|(".+"))@(([^<>()[\],;:\s@"]+\.)+[^<>()[\],;:\s@"]{2,})$/i;
        if(!emailRe.test(registerData.email)){
            setAlertMessage(prevState => ({
                ...prevState,
                email: "Email is not valid!"
            }));
            formIsValid = false;
        }

        const passwordRe = /^(?=.*?[A-Z])(?=(.*[a-z]){1,})(?=(.*[\d]){1,})(?=(.*[\W]){1,})(?!.*\s).{8,}$/i;
        if(!passwordRe.test(registerData.password)) {
            setAlertMessage(prevState => ({
                ...prevState,
                password: "Password requirements: Minimum 8 characters, at least 1 uppercase letter, 1 lowercase letter, 1 number and 1 special character:"
            }));
            formIsValid = false;
        }

        if(registerData.password !== registerData.confirmPassword) {
            setAlertMessage(prevState => ({
                ...prevState,
                password: "Password and confirm password are not the same!"
            }));
            formIsValid = false;
        }

        if(!registerData.firstname) {
            setAlertMessage(prevState => ({
                ...prevState,
                firstname: "Firstname field can not be empty!"
            }));
            formIsValid = false;
        }

        if(!registerData.lastname) {
            setAlertMessage(prevState => ({
                ...prevState,
                lastname: "Lastname field can not be empty!"
            }));
            formIsValid = false;
        }

       return formIsValid;
   }

    const registerClicked = async (e: Event) => {
        e.preventDefault();

        if (!handleValidation()) {
            return;
        };

        const registerDTO = {
            email: registerData.email,
            password: registerData.password,
            firstname: registerData.firstname,
            lastname: registerData.lastname,
        }

        let response = await IdentityService.Register('account/register', registerDTO);
        if (!response.ok) {
            setAlertMessage(prevState => ({
                ...prevState,
                error: response.messages!
            }));
        } else {
            appState.setAuthInfo(response.data!.token, response.data!.firstname, response.data!.lastname);
        }
    }

    const handleChange = (target: HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement) => {
        switch (target.id) {
            case 'email':
                setFormValues({ ...registerData, email: target.value });
                return
            case 'password':
                setFormValues({ ...registerData, password: target.value });
                return
            case 'confirmPassword':
                setFormValues({ ...registerData, confirmPassword: target.value });
                return
            case 'firstname':
                setFormValues({ ...registerData, firstname: target.value });
                return
            case 'lastname':
                setFormValues({ ...registerData, lastname: target.value });
                return
        }
    }

    return (
        <>
            { appState.token !== null ? <Redirect to="/" /> : null}
            <Alert show={alertMessage.error !== ''} message={alertMessage.error} alertClass={EAlertClass.Danger} />
            <div className="row">
                <div className="col-md-4">
                    <form onSubmit={(e) => registerClicked(e.nativeEvent)}>
                        <h4>Create new account</h4>
                        <hr />
                        <div className="form-group">
                            <label asp-for="Input.Email">Email</label>
                            <input value={registerData.email} onChange={(e) => handleChange(e.target)} maxLength={100} className="form-control" id="email"/>
                            <Alert show={alertMessage.email !== ''} message={alertMessage.email} alertClass={EAlertClass.Danger} />
                        </div>
                        <div className="form-group">
                            <label asp-for="Input.Password">Password</label>
                            <input value={registerData.password} onChange={(e) => handleChange(e.target)} maxLength={100} className="form-control" type="password" id="password"/>
                            <Alert show={alertMessage.password !== ''} message={alertMessage.password} alertClass={EAlertClass.Danger} />
                        </div>
                        <div className="form-group">
                            <label asp-for="Input.ConfirmPassword">Confirme password</label>
                            <input value={registerData.confirmPassword} onChange={(e) => handleChange(e.target)} maxLength={100} className="form-control" type="password" id="confirmPassword"/>
                            <Alert show={alertMessage.confirmPassword !== ''} message={alertMessage.confirmPassword} alertClass={EAlertClass.Danger} />
                        </div>
                        <div className="form-group">
                            <label asp-for="Input.FirstName">Firstname</label>
                            <input value={registerData.firstname} onChange={(e) => handleChange(e.target)} maxLength={128} className="form-control" id="firstname"/>
                            <Alert show={alertMessage.firstname !== ''} message={alertMessage.firstname} alertClass={EAlertClass.Danger} />
                        </div>
                        <div className="form-group">
                            <label asp-for="Input.LastName">Lastname</label>
                            <input value={registerData.lastname} onChange={(e) => handleChange(e.target)} maxLength={128} className="form-control" id="lastname"/>
                            <Alert show={alertMessage.lastname !== ''} message={alertMessage.lastname} alertClass={EAlertClass.Danger} />
                        </div>
                        <button onClick={(e) => registerClicked(e.nativeEvent)} type="submit" className="btn btn-primary">Register</button>
                        <Link className="ml-2" to="/Identity/Login">Back to login</Link>
                    </form>
                </div>
            </div>
        </>
    );
}

export default Register;

// exam-vue/src/containers/identity/Register.vue
<template>
    <Alert :alertInfo="errors.generalError" />
    <div class="row">
        <div class="col-md-4">
            <h4>Create new account</h4>
            <hr />
            <div class="form-group">
                <label>Email</label>
                <input v-model="registerDTO.email" :maxLength="100" class="form-control" id="email"/>
                <Alert :alertInfo="errors.email" />
            </div>
            <div class="form-group">
                <label>Password</label>
                <input v-model="registerDTO.password" :maxLength="100" class="form-control" type="password" id="password"/>
                <Alert :alertInfo="errors.password" />
            </div>
            <div class="form-group">
                <label>Confirme password</label>
                <input v-model="confirmPassword" :maxLength="100" class="form-control" type="password" id="confirmPassword"/>
            </div>
            <div class="form-group">
                <label>Firstname</label>
                <input v-model="registerDTO.firstname" :maxLength="128" class="form-control" id="firstname"/>
                <Alert :alertInfo="errors.firstname" />
            </div>
            <div class="form-group">
                <label>Lastname</label>
                <input v-model="registerDTO.lastname" :maxLength="128" class="form-control" id="lastname"/>
                <Alert :alertInfo="errors.lastname" />
            </div>
            <button @click="registerClicked()" type="submit" class="btn btn-primary">
                Register
            </button>
            <router-link class="ml-2" to="/Identity/Login">
                Login
            </router-link>
        </div>
    </div>
</template>
<script lang="ts">
import { Options, Vue } from "vue-class-component";
import store from "@/store/index";
import { IdentityService } from "@/services/identity-service";
import Alert from "@/components/Alert.vue";
import { RegisterErrors } from "@/domain/errors/RegisterErrors";
import { Register as RegisterDTO } from "@/domain/DTO/Register";

@Options({
    components: {
        Alert
    },
    props: {},
})
export default class Register extends Vue {
    errors: RegisterErrors = new RegisterErrors();
    registerDTO: RegisterDTO = new RegisterDTO();
    confirmPassword: string = "";

    async registerClicked(): Promise<void> {
        if (!this.handleValidation()) {
            return;
        }

        const response = await IdentityService.Register('/Account/Register', this.registerDTO);
        if (!response.ok && response.messages != null) {
            this.errors.generalError.message = response.messages
        } else {
            store.commit("logIn", response.data);
            this.$router.push("/");
        }
    }

    handleValidation(): boolean {
        let formIsValid = true;

        this.errors = new RegisterErrors();

        const emailRe = /^(([^<>()[\].,;:\s@"]+(\.[^<>()[\],;:\s@"]+)*)|(".+"))@(([^<>()[\],;:\s@"]+\.)+[^<>()[\],;:\s@"]{2,})$/i;
        if (!emailRe.test(this.registerDTO.email)) {
            this.errors.email.message = "Email is not valid!"
            formIsValid = false;
        }

        const passwordRe = /^(?=.*?[A-Z])(?=(.*[a-z]){1,})(?=(.*[\d]){1,})(?=(.*[\W]){1,})(?!.*\s).{8,}$/i;
        if (!passwordRe.test(this.registerDTO.password)) {
            this.errors.password.message = "Password requirements: Minimum 8 characters, at least 1 uppercase letter, 1 lowercase letter, 1 number and 1 special character:"
            formIsValid = false;
        }

        if (this.registerDTO.password !== this.confirmPassword) {
            this.errors.password.message = "Password and confirm password are not the same!";
            formIsValid = false;
        }

        if (!this.registerDTO.firstname) {
            this.errors.firstname.message = "Firstname field can not be empty!"
            formIsValid = false;
        }

        if (!this.registerDTO.lastname) {
            this.errors.lastname.message = "Lastname field can not be empty!"
            formIsValid = false;
        }

        return formIsValid;
    }
}
</script>
