// exam-react/src/components/Footer.tsx
import { Link } from "react-router-dom";

const Footer = () => (
    <footer className="footer bg-dark text-center text-lg-start text-light">
        <div className="container">
            &copy; 2021 - Bloody -
            <Link className="text-info" to="/Privacy"> Privacy</Link>
        </div>
    </footer>
)

export default Footer;

// exam-vue/src/components/Footer.vue
<template>
    <footer class="footer bg-dark text-center text-lg-start text-light">
        <div class="container">
            2021
            <router-link class="text-info" to="/privacy">
                Privacy
            </router-link>
        </div>
    </footer>
</template>
<script lang="ts">
import { Options, Vue } from "vue-class-component";

@Options({
    components: {},
    props: {},
})
export default class Footer extends Vue {}
</script>
