// blood-donation-system-vue/src/views/blood-test/Index.vue
<template>
        <h1>Blood tests</h1>

    <p>
        <router-link class="nav-link text-dark" to="/bloodtest/Create">Create new</router-link>
    </p>

    <table class="table">
        <thead>
            <tr>
                <th>Allowed</th>
                <th>Donor</th>
                <th>Doctor</th>
                <th>Created at</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <tr v-for="item in bloodTests" :key="item.id">
                <td>{{ item.allowed }}</td>
                <td>{{ item.donor.fullName }}</td>
                <td>{{ item.doctor.fullName }}</td>
                <td>{{ item.createAt }}</td>
                <td>
                    <router-link :to="'/bloodtest/details/' + item.id">Details</router-link>
                </td>
            </tr>
        </tbody>
    </table>
</template>

<script lang="ts">
import { Options, Vue } from "vue-class-component";
import store from "@/store/index";
import { BaseService } from "@/services/base-service";
import { BloodTest } from "@/domain/BloodTest";

@Options({
    components: {},
    props: {},
})
export default class BloodTestIndex extends Vue {
    bloodTests: BloodTest[] | null = null;

    get isUserLoggedIn(): boolean {
        return store.state.token != null;
    }

    mounted(): void {
        const service = new BaseService<BloodTest>(
            "BloodTest",
            store.state.token ? store.state.token : undefined
        );
        service.getAll().then((data) => {
            this.bloodTests = data.data!;
        });
    }
}
</script>

// blood-donation-system-react/src/containers/bloodTest/Index.tsx
import { useEffect, useState } from "react";
import { useContext } from "react";
import { Link } from "react-router-dom";
import Loader from "../../components/Loader";
import { AppContext } from "../../context/AppContext";
import { BloodTest } from "../../dto/BloodTest";
import { BaseService } from "../../services/base-service";
import { EPageStatus } from "../../types/EPageStatus";
 
const RowDisplay = (props: { bloodTest: BloodTest }) => (
    <>
        <td>{props.bloodTest.allowed ? '✔' : '❌'}</td>
        <td>{props.bloodTest.donor!.fullName}</td>
        <td>{props.bloodTest.doctor!.fullName}</td>
        <td>{props.bloodTest.createAt}</td>
        <td>
            <Link to={'/BloodTest/' + props.bloodTest.id}>Details</Link>
        </td>
    </>
);

const BloodTestIndex = () => {
    const [bloodTests, setBloodTests] = useState([] as BloodTest[]);
    const [pageStatus, setPageStatus] = useState({ pageStatus: EPageStatus.Loading, statusCode: -1 });
    const appState = useContext(AppContext);

    const loadData = async () => {
        let result = await BaseService.getAll<BloodTest>('BloodTest', appState.token!);

        if (result.ok && result.data) {
            setPageStatus({ pageStatus: EPageStatus.OK, statusCode: 0 });
            setBloodTests(result.data);
        } else {
            setPageStatus({ pageStatus: EPageStatus.Error, statusCode: result.statusCode });
        }
    }

    useEffect(() => {
        loadData();
    }, []); // eslint-disable-line react-hooks/exhaustive-deps

    return (
        <>
            <h1>Blood tests</h1>
            <table className="table">
                <thead>
                    <tr>
                        <th>Allowed</th>
                        <th>Donor</th>
                        <th>Doctor</th>
                        <th>Created at</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    {bloodTests.map(bloodTest =>
                        <tr key={bloodTest.id.toString()}>
                            <RowDisplay bloodTest={bloodTest} />
                        </tr>)
                    }
                </tbody>
            </table>
            <Loader {...pageStatus} />
        </>
    );
}

export default BloodTestIndex;
