// blood-donation-system-vue/src/views/blood-donate/Create.vue
<template>
<h1>Create</h1>

<h4>Blood donation</h4>
<hr/>
<div class="row">
    <div class="col-md-4">
        <div class="form-group">
            <label class="control-label">Donor</label>
            <select class="form-control" v-model="bloodDonate.donorId">
                <option v-for="patient in patients" :key="patient.id" :value="patient.id">
                    {{ patient.fullName }}
                </option>
            </select>
        </div>
        <div class="form-group">
            <label class="control-label">Doctor</label>
            <select class="form-control" v-model="bloodDonate.doctorId">
                <option v-for="doctor in doctors" :key="doctor.id" :value="doctor.id">
                    {{ doctor.fullName }}
                </option>
            </select>
        </div>
        <div class="form-group">
            <label class="control-label">Blood test</label>
            <select class="form-control" v-model="bloodDonate.bloodTestId" >
                <option v-for="bloodTest in bloodTests" :key="bloodTest.id" :value="bloodTest.id" >
                    {{ bloodTest.overviewData }}
                </option>
            </select>
        </div>
        <div class="form-group">
            <label class="control-label">Amount</label>
            <input class="form-control" v-model="bloodDonate.amount" />
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-primary" v-on:click="create()">Create</button>
        </div>
    </div>
</div>

</template>

<script lang="ts">
import { Options, Vue } from "vue-class-component";
import store from "@/store/index";
import { BaseService } from "@/services/base-service";
import { BloodDonate } from "@/domain/BloodDonate";
import { Person } from "@/domain/Person";
import { BloodTest } from "@/domain/BloodTest";

@Options({
    components: {},
    props: {
        id: String,
    },
})
export default class BloodDonateCreate extends Vue {
    id!: string;
    bloodDonate: BloodDonate = {
        id: "00000000-0000-0000-0000-000000000000",
        createdBy: "-",
        createAt: "0001-01-01T00:00:00",
        updateBy: "-",
        updatedAt: "0001-01-01T00:00:00",
        donorId: "",
        donor: null,
        doctorId: "",
        doctor: null,
        bloodTestId: "",
        blootest: null,
        bloodGroupId: "00000000-0000-0000-0000-000000000000",
        bloodGroup: null,
        amount: 0,
        available: false,
        expireDate: "0001-01-01T00:00:00",
    }

    patients: Person[] = [];
    doctors: Person[] = [];
    bloodTests: BloodTest[] = [];

    mounted(): void {
        const servicePerson = new BaseService<Person>(
            "Persons",
            store.state.token ? store.state.token : undefined
        );
        servicePerson.getAll(["personType=patient"]).then((data) => {
            this.patients = data.data!;
        });
        servicePerson.getAll(["personType=doctor"]).then((data) => {
            this.doctors = data.data!;
        });

        const serviceBloodGroup = new BaseService<BloodTest>(
            "BloodTest/minimum",
            store.state.token ? store.state.token : undefined
        );
        serviceBloodGroup.getAll().then((data) => {
            this.bloodTests = data.data!;
        });
    }

    create(): void {
        const service = new BaseService<BloodDonate>(
            "BloodDonate",
            store.state.token ? store.state.token : undefined
        );
        console.log(JSON.stringify(this.bloodDonate))
        service.post(this.bloodDonate);
        this.$router.push("/Blooddonate");
    }
}
</script>

// blood-donation-system-react/src/containers/bloodDonate/Create.tsx
import { useEffect, useState } from "react";
import { useContext } from "react";
import { AppContext } from "../../context/AppContext";
import { BloodDonate } from "../../dto/BloodDonate";
import { BloodTest } from "../../dto/BloodTest";
import { Person } from "../../dto/Person";
import { BaseService } from "../../services/base-service";
import { EPageStatus } from "../../types/EPageStatus";
import Alert, { EAlertClass } from "../../components/Alert";
import { Redirect } from "react-router-dom";
import Loader from "../../components/Loader";
import { IFormProps } from "../../types/IFormProps";

const initialFormValues: BloodDonate = {
    id: "00000000-0000-0000-0000-000000000000",
    createdBy: "-",
    createAt: "0001-01-01T00:00:00",
    updateBy: "-",
    updatedAt: "0001-01-01T00:00:00",
    donorId: "",
    donor: null,
    doctorId: "",
    doctor: null,
    bloodTestId: "",
    blootest: null,
    bloodGroupId: "00000000-0000-0000-0000-000000000000",
    bloodGroup: null,
    amount: 0,
    available: true,
    expireDate: "0001-01-01T00:00:00",
};

const FormView = (props: IFormProps<BloodDonate>) => {
    const validationTemplate = {
        "error": "",
        "amount": "",
        "donor": "",
        "doctor": "",
        "bloodTest": ""}

    const [patients, setPatients] = useState([] as Person[]);
    const [doctors, setDoctors] = useState([] as Person[]);
    const [bloodTests, setBloodTests] = useState([] as BloodTest[]);
    const [submit, setSubmit] = useState("");

    const [pageStatus, setPageStatus] = useState({ pageStatus: EPageStatus.Loading, statusCode: -1 });
    const [alertMessage, setAlertMessage] = useState(validationTemplate);
    const appState = useContext(AppContext);

    const loadData = async () => {
        let resultPatients = await BaseService.getAll<Person>('/Persons/personType=Patient', appState.token!);
        let resultDoctors = await BaseService.getAll<Person>('/Persons/personType=Doctor', appState.token!);
        let resultBloodTests = await BaseService.getAll<BloodTest>('/BloodTest/minimum', appState.token!);

        if (resultPatients.ok && resultPatients.data &&
            resultDoctors.ok && resultDoctors.data &&
            resultBloodTests.ok && resultBloodTests.data) {
            setPageStatus({ pageStatus: EPageStatus.OK, statusCode: 0 });
            setPatients(resultPatients.data);
            setDoctors(resultDoctors.data);
            setBloodTests(resultBloodTests.data);
        } else {
            setPageStatus({ pageStatus: EPageStatus.Error, statusCode: resultBloodTests.statusCode });
        }
    }

    useEffect(() => {
        loadData();
    }, []); // eslint-disable-line react-hooks/exhaustive-deps

    const handleValidation = () => {
        let formIsValid = true;

        setAlertMessage(validationTemplate);

        if(props.values.amount === 0){
            setAlertMessage(prevState => ({
                ...prevState,
                "amount": "Amount can not be 0!"
            }));
            formIsValid = false;
        }

        if(props.values.donorId === ""){
            setAlertMessage(prevState => ({
                ...prevState,
                "donor": "Donor field can not be empty!"
            }));
            formIsValid = false;
        }

        if(props.values.doctorId === ""){
            setAlertMessage(prevState => ({
                ...prevState,
                "doctor": "Doctor field can not be empty!"
            }));
            formIsValid = false;
        }

        if(props.values.bloodTestId === ""){
            setAlertMessage(prevState => ({
                ...prevState,
                "bloodTest": "bloodTest field can not be empty!"
            }));
            formIsValid = false;
        }

       return formIsValid;
   }

    const createSubmit = async (e: Event) => {
        e.preventDefault();

        if (!handleValidation()) {
            return;
        }

        let response = await BaseService.post("BloodDonate", props.values, appState.token!);
        if (!response.ok) {
            setAlertMessage(prevState => ({
                ...prevState,
                "error": response.messages!
            }));

        } else {
            setAlertMessage(prevState => ({
                ...prevState,
                "error": ""
            }));
            setSubmit(response.data!.id);
        }
    }

    return (
        <>
        <form>
            { submit !== "" ? <Redirect to={'/BloodDonate/' + submit} /> : null}
            <Alert show={alertMessage.error !== ''} message={alertMessage.error} alertClass={EAlertClass.Danger} />
            <div className="form-group">
                <label className="control-label">Donor</label>
                <select value={props.values.donorId ?? 0} onChange={(e) => props.handleChange(e.target)} className="form-control" id="donor">
                    <option></option>
                    {patients.map(patient => {
                        return <option key={patient.id} value={patient.id}>{patient.fullName}</option>
                    })}
                </select>
                <Alert show={alertMessage.donor !== ''} message={alertMessage.donor} alertClass={EAlertClass.Danger} />
            </div>

            <div className="form-group">
                <label className="control-label">Doctor</label>
                <select value={props.values.doctorId ?? 0} onChange={(e) => props.handleChange(e.target)} className="form-control" id="doctor">
                    <option></option>
                    {doctors.map(doctor => {
                        return <option key={doctor.id} value={doctor.id}>{doctor.fullName}</option>
                    })}
                </select>
                <Alert show={alertMessage.doctor !== ''} message={alertMessage.doctor} alertClass={EAlertClass.Danger} />
            </div>

            <div className="form-group">
                <label className="control-label">Blood test</label>
                <select value={props.values.bloodTestId ?? 0} onChange={(e) => props.handleChange(e.target)} className="form-control" id="bloodTest">
                    <option></option>
                    {bloodTests.map(bloodTest => {
                        return <option key={bloodTest.id} value={bloodTest.id}>{bloodTest.overviewData}</option>
                    })}
                </select>
                <Alert show={alertMessage.bloodTest !== ''} message={alertMessage.bloodTest} alertClass={EAlertClass.Danger} />
            </div>

            <div className="form-group">
                <label className="control-label">Amount</label>
                <input value={props.values.amount ?? 0} onChange={(e) => props.handleChange(e.target)} className="form-control" id="amount" />
                <Alert show={alertMessage.amount !== ''} message={alertMessage.amount} alertClass={EAlertClass.Danger} />
            </div>

            <div className="form-group">
                <button type="submit" onClick={(e) => createSubmit(e.nativeEvent)} className="btn btn-primary">Create</button>
            </div>
        </form>
        <Loader {...pageStatus} />
        </>
    );
}


const BloodDonateCreate = () => {

    const [formValues, setFormValues] = useState(initialFormValues);

    const handleChange = (target: HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement) => {
        switch (target.id) {
            case 'doctor':
                setFormValues({ ...formValues, doctorId: target.value });
                return;
            case 'donor':
                setFormValues({ ...formValues, donorId: target.value });
                return;
            case 'bloodTest':
                setFormValues({ ...formValues, bloodTestId: target.value });
                return;
            case 'amount':
                setFormValues({ ...formValues, amount: target.value === "" ? 0 : parseInt(target.value) });
                return;
        }
    }

    return (
        <>
            <h1>Create</h1>
            <h4>Blood donate</h4>
            <hr />
            <div className="row">
                <div className="col-md-4">
                    <FormView values={formValues} handleChange={handleChange} />
                </div>
            </div>
        </>
    )

}

export default BloodDonateCreate;
