// blood-donation-system-vue/src/views/blood-donate/Index.vue
<template>
    <h1>Blood donations</h1>

    <p>
        <router-link class="nav-link text-dark" to="/Blooddonate/Create">Create new</router-link>
    </p>

    <table class="table">
        <thead>
            <tr>
                <th>Blood group</th>
                <th>Amount</th>
                <th>Donor</th>
                <th>Doctor</th>
                <th>Created at</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <tr v-for="item in bloodDonates" :key="item.id">
                <td>{{ item.bloodGroup.bloodGroupValue }}</td>
                <td>{{ item.amount }}</td>
                <td>{{ item.donor.fullName }}</td>
                <td>{{ item.doctor.fullName }}</td>
                <td>{{ item.createAt }}</td>
                <td>
                    <router-link :to="'/Blooddonate/details/' + item.id">Details</router-link>
                </td>
            </tr>
        </tbody>
    </table>
</template>

<script lang="ts">
import { Options, Vue } from "vue-class-component";
import store from "@/store/index";
import { BaseService } from "@/services/base-service";
import { BloodDonate } from "@/domain/BloodDonate";

@Options({
    components: {},
    props: {},
})
export default class BloodDonateIndex extends Vue {
    bloodDonates: BloodDonate[] | null = null;

    get isUserLoggedIn(): boolean {
        return store.state.token != null;
    }

    mounted(): void {
        const service = new BaseService<BloodDonate>(
            "BloodDonate",
            store.state.token ? store.state.token : undefined
        );
        service.getAll().then((data) => {
            this.bloodDonates = data.data!;
        });
    }
}
</script>

// blood-donation-system-react/src/containers/bloodDonate/Index.tsx
import { useEffect, useState } from "react";
import { useContext } from "react";
import { Link } from "react-router-dom";
import Loader from "../../components/Loader";
import { AppContext } from "../../context/AppContext";
import { BloodDonate } from "../../dto/BloodDonate";
import { BaseService } from "../../services/base-service";
import { EPageStatus } from "../../types/EPageStatus";

const RowDisplay = (props: { bloodDonate: BloodDonate }) => (
    <>
        <td>{props.bloodDonate.bloodGroup!.bloodGroupValue}</td>
        <td>{props.bloodDonate.amount}</td>
        <td>{props.bloodDonate.donor!.fullName}</td>
        <td>{props.bloodDonate.doctor!.fullName}</td>
        <td>{props.bloodDonate.createAt}</td>
        <td>
            <Link to={'/BloodDonate/' + props.bloodDonate.id}>Details</Link>
        </td>
    </>
);

const BloodDonateIndex = () => {
    const [bloodDonates, setBloodDonates] = useState([] as BloodDonate[]);
    const [pageStatus, setPageStatus] = useState({ pageStatus: EPageStatus.Loading, statusCode: -1 });
    const appState = useContext(AppContext);

    const loadData = async () => {
        let result = await BaseService.getAll<BloodDonate>('/BloodDonate', appState.token!);

        if (result.ok && result.data) {
            setPageStatus({ pageStatus: EPageStatus.OK, statusCode: 0 });
            setBloodDonates(result.data);
        } else {
            setPageStatus({ pageStatus: EPageStatus.Error, statusCode: result.statusCode });
        }
    }

    useEffect(() => {
        loadData();
    }, []); // eslint-disable-line react-hooks/exhaustive-deps

    return (
        <>
            <h1>Blood donations</h1>
            <table className="table">
                <thead>
                    <tr>
                        <th>Blood group</th>
                        <th>Amount</th>
                        <th>Donor</th>
                        <th>Doctor</th>
                        <th>Created at</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    {bloodDonates.map(bloodDonate =>
                        <tr key={bloodDonate.id.toString()}>
                            <RowDisplay bloodDonate={bloodDonate} />
                        </tr>)
                    }
                </tbody>
            </table>
            <Loader {...pageStatus} />
        </>
    );
}

export default BloodDonateIndex;
