// blood-donation-system-react/src/containers/bloodTest/Create.tsx
import { useEffect, useState } from "react";
import { useContext } from "react";
import { Redirect } from "react-router-dom";
import Alert, { EAlertClass } from "../../components/Alert";
import { AppContext } from "../../context/AppContext";
import { BloodGroup } from "../../dto/BloodGroup";
import { BloodTest } from "../../dto/BloodTest";
import { Person } from "../../dto/Person";
import { BaseService } from "../../services/base-service";
import { EPageStatus } from "../../types/EPageStatus";
import Loader from "../../components/Loader";
import { IFormProps } from "../../types/IFormProps";

const initialFormValues: BloodTest = {
    id: "00000000-0000-0000-0000-000000000000",
    createdBy: "-",
    createAt: "0001-01-01T00:00:00",
    updateBy: "-",
    updatedAt: "0001-01-01T00:00:00",
    allowed: false,
    comments: "",
    donorId: "",
    donor: null,
    doctorId: "",
    doctor: null,
    bloodGroupId: "",
    bloodGroup: null,
    overviewData: ""
};

const FormView = (props: IFormProps<BloodTest>) => {
    const validationTemplate = {
        "error": "",
        "donor": "",
        "doctor": "",
        "bloodGroup": ""
    }

    const [patients, setPatients] = useState([] as Person[]);
    const [doctors, setDoctors] = useState([] as Person[]);
    const [bloodGroups, setBloodGroups] = useState([] as BloodGroup[]);
    const [submit, setSubmit] = useState("");

    const [pageStatus, setPageStatus] = useState({ pageStatus: EPageStatus.Loading, statusCode: -1 });
    const [alertMessage, setAlertMessage] = useState(validationTemplate);

    const appState = useContext(AppContext);

    const loadData = async () => {
        let resultPatients = await BaseService.getAll<Person>('/Persons/personType=Patient', appState.token!);
        let resultDoctors = await BaseService.getAll<Person>('/Persons/personType=Doctor', appState.token!);
        let resultBloodGroup = await BaseService.getAll<BloodGroup>('/BloodGroup', appState.token!);

        if (resultPatients.ok && resultPatients.data &&
            resultDoctors.ok && resultDoctors.data &&
            resultBloodGroup.ok && resultBloodGroup.data) {
            setPageStatus({ pageStatus: EPageStatus.OK, statusCode: 0 });
            setPatients(resultPatients.data);
            setDoctors(resultDoctors.data);
            setBloodGroups(resultBloodGroup.data);
        } else {
            setPageStatus({ pageStatus: EPageStatus.Error, statusCode: resultBloodGroup.statusCode });
        }
    }

    const handleValidation = () => {
        let formIsValid = true;

        setAlertMessage(validationTemplate);

        if(props.values.donorId === ""){
            setAlertMessage(prevState => ({
                ...prevState,
                "donor": "Donor field can not be empty!"
            }));
            formIsValid = false;
        }

        if(props.values.doctorId === ""){
            setAlertMessage(prevState => ({
                ...prevState,
                "doctor": "Doctor field can not be empty!"
            }));
            formIsValid = false;
        }

        if(props.values.bloodGroupId === ""){
            setAlertMessage(prevState => ({
                ...prevState,
                "bloodGroup": "blood group field can not be empty!"
            }));
            formIsValid = false;
        }

       return formIsValid;
   }

    const createSubmit = async (e: Event) => {
        e.preventDefault();

        if (!handleValidation()) {
            return;
        }

        let response = await BaseService.post("BloodTest", props.values, appState.token!);
        if (!response.ok) {
            setAlertMessage(prevState => ({
                ...prevState,
                "error": response.messages!
            }));
        } else {
            setSubmit(response.data!.id);
        }
    }

    useEffect(() => {
        loadData();
    }, []); // eslint-disable-line react-hooks/exhaustive-deps

    return (
        <>
            <form>
                {submit !== "" ? <Redirect to={'/BloodTest/' + submit} /> : null}
                <Alert show={alertMessage.error !== ''} message={alertMessage.error} alertClass={EAlertClass.Danger} />
                <div className="form-group">
                    <label className="control-label">Doctor</label>
                    <select value={props.values.doctorId ?? 0} onChange={(e) => props.handleChange(e.target)} className="form-control" id="doctor">
                        <option></option>
                        {doctors.map(doctor => {
                            return <option key={doctor.id} value={doctor.id}>{doctor.fullName}</option>
                        })}
                    </select>
                    <Alert show={alertMessage.doctor !== ''} message={alertMessage.doctor} alertClass={EAlertClass.Danger} />
                </div>

                <div className="form-group">
                    <label className="control-label">Donor</label>
                    <select value={props.values.donorId ?? 0} onChange={(e) => props.handleChange(e.target)} className="form-control" id="donor">
                        <option></option>
                        {patients.map(patient => {
                            return <option key={patient.id} value={patient.id}>{patient.fullName}</option>
                        })}
                    </select>
                    <Alert show={alertMessage.donor !== ''} message={alertMessage.donor} alertClass={EAlertClass.Danger} />
                </div>

                <div className="form-group">
                    <label className="control-label">Blood group</label>
                    <select value={props.values.bloodGroupId ?? 0} onChange={(e) => props.handleChange(e.target)} className="form-control" id="bloodGroup">
                        <option></option>
                        {bloodGroups.map(bloodGroup => {
                            return <option key={bloodGroup.id} value={bloodGroup.id}>{bloodGroup.bloodGroupValue}</option>
                        })}
                    </select>
                    <Alert show={alertMessage.bloodGroup !== ''} message={alertMessage.bloodGroup} alertClass={EAlertClass.Danger} />
                </div>

                <div className="form-group col-3">
                    <label className="control-label">Allowed</label>
                    <input checked={props.values.allowed ?? false} onChange={(e) => props.handleChange(e.target)} type="checkbox" className="form-control" id="allowed" />
                </div>

                <div className="form-group">
                    <label htmlFor="formTextArea">Comments</label>
                    <textarea value={props.values.comments ?? 0} onChange={(e) => props.handleChange(e.target)} className="form-control" id="comments" rows={3}></textarea>
                </div>

                <div className="form-group">
                    <button type="submit" onClick={(e) => createSubmit(e.nativeEvent)} className="btn btn-primary">Create</button>
                </div>
            </form>
            <Loader {...pageStatus} />
        </>
    );
}


const BloodTestCreate = () => {
    const [formValues, setFormValues] = useState(initialFormValues);

    const handleChange = (target: HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement) => {
        switch (target.id) {
            case 'doctor':
                setFormValues({ ...formValues, doctorId: target.value });
                return
            case 'donor':
                setFormValues({ ...formValues, donorId: target.value });
                return
            case 'bloodGroup':
                setFormValues({ ...formValues, bloodGroupId: target.value });
                return
            case 'allowed':
                setFormValues({ ...formValues, allowed: (target as HTMLInputElement).checked });
                return
            case 'comments':
                setFormValues({ ...formValues, comments: target.value });
                return
        }
    }

    return (
        <>
            <h1>Create</h1>
            <h4>Blood test</h4>
            <hr />
            <div className="row">
                <div className="col-md-4">
                    <FormView values={formValues} handleChange={handleChange} />
                </div>
            </div>
        </>
    )

}

export default BloodTestCreate;

// exam-vue/src/containers/blood-donate/Create.vue
<template>
<h1>Create</h1>

<h4>Blood donation</h4>
<hr/>
<div class="row">
    <div class="col-md-4">
        <Alert :alertInfo="errors.generalError" />
        <div class="form-group">
            <label class="control-label">Donor</label>
            <select class="form-control" v-model="bloodDonate.donorId" >
                <option v-for="patient in patients" :key="patient.id" :value="patient.id">
                    {{ patient.fullName }}
                </option>
            </select>
            <Alert :alertInfo="errors.donor" />
        </div>
        <div class="form-group">
            <label class="control-label">Doctor</label>
            <select class="form-control" v-model="bloodDonate.doctorId">
                <option v-for="doctor in doctors" :key="doctor.id" :value="doctor.id">
                    {{ doctor.fullName }}
                </option>
            </select>
            <Alert :alertInfo="errors.doctor" />
        </div>
        <div class="form-group">
            <label class="control-label">Blood test</label>
            <select class="form-control" v-model="bloodDonate.bloodTestId" >
                <option v-for="bloodTest in bloodTests" :key="bloodTest.id" :value="bloodTest.id" >
                    {{ bloodTest.overviewData }}
                </option>
            </select>
            <Alert :alertInfo="errors.bloodTest" />
        </div>
        <div class="form-group">
            <label class="control-label">Amount</label>
            <input class="form-control" v-model="bloodDonate.amount" />
            <Alert :alertInfo="errors.amount" />
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-primary" v-on:click="create()">Create</button>
        </div>
        <Loader :pageLoader="pageLoader" />
    </div>
</div>

</template>

<script lang="ts">
import { Options, Vue } from "vue-class-component";
import store from "@/store/index";
import { BaseService } from "@/services/base-service";
import { BloodDonate } from "@/domain/DTO/BloodDonate";
import { Person } from "@/domain/DTO/Person";
import { BloodTest } from "@/domain/DTO/BloodTest";
import { BloodDonateErrors } from "@/domain/errors/BloodDonateErrors";
import { EPageStatus } from "@/types/EPageStatus";
import { PageLoader } from "@/types/PageLoader";
import Loader from "@/components/Loader.vue";
import Alert from "@/components/Alert.vue";

@Options({
    components: {
        Loader,
        Alert
    },
    props: {
    },
})
export default class BloodDonateCreate extends Vue {
    errors: BloodDonateErrors = new BloodDonateErrors();
    pageLoader: PageLoader = { pageStatus: EPageStatus.Loading, statusCode: -1 };

    bloodDonate: BloodDonate = new BloodDonate();
    patients: Person[] = [];
    doctors: Person[] = [];
    bloodTests: BloodTest[] = [];

    async mounted(): Promise<void> {
        const resultPatients = await BaseService.getAll<Person>("/Persons", store.state.token as string);
        const resultDoctors = await BaseService.getAll<Person>("/Persons/personType=doctor", store.state.token as string);
        const resultBloodTests = await BaseService.getAll<BloodTest>("/BloodTest/minimum", store.state.token as string);

        if (resultPatients.ok && resultPatients.data &&
            resultDoctors.ok && resultDoctors.data &&
            resultBloodTests.ok && resultBloodTests.data) {
            this.pageLoader = { pageStatus: EPageStatus.OK, statusCode: 0 }

            this.patients = resultPatients.data as Person[];
            this.doctors = resultDoctors.data as Person[];
            this.bloodTests = resultBloodTests.data as BloodTest[];
        } else {
            this.pageLoader = {
                pageStatus: EPageStatus.Error,
                statusCode: (!resultPatients.ok ? resultPatients
                    : !resultDoctors.ok ? resultDoctors
                        : resultBloodTests).statusCode
            }
        }
    }

    async create(): Promise<void> {
        if (!this.handleValidation()) {
            return;
        }

        const response = await BaseService.post("BloodDonate", this.bloodDonate, store.state.token as string);
        if (response.ok != null && response.messages != null) {
            this.errors.generalError.message = response.messages
        } else if (response.data != null) {
            this.$router.push("/Blooddonate/" + response.data.id);
        }
    }

    handleValidation(): boolean {
        let formIsValid = true;

        this.errors = new BloodDonateErrors();

        if (!this.bloodDonate.amount || this.bloodDonate.amount === "0") {
            this.errors.amount.message = "Amount can not be 0!";
            formIsValid = false;
        }

        if (!this.bloodDonate.donorId) {
            this.errors.donor.message = "Donor field can not be empty!";
            formIsValid = false;
        }

        if (!this.bloodDonate.doctorId) {
            this.errors.doctor.message = "Doctor field can not be empty!";
            formIsValid = false;
        }

        if (!this.bloodDonate.bloodTestId) {
            this.errors.bloodTest.message = "bloodTest field can not be empty!";
            formIsValid = false;
        }

        return formIsValid;
    }
}
</script>
